### ISSUE TITLE
Error in function plot_optimization_progress() (something about units)

### ISSUE THREAD

**Issue by tpilz** [TillF/ppso#1]
When running function `plot_optimization_progress()` I suddenly get the following error message:

```
Error in UseMethod("units<-") : 
  no applicable method for 'units<-' applied to an object of class "logical"
```
Until a few days ago everything worked fine. I guess it is related to `goodness_plot` when plotting function evaluation times.

I am using version 0.9-9994 of `ppso`.

**Comment by TillF** [comment]
Could you please provide the files dds.log and dds.pro?
