### ISSUE TITLE
Multiple optimizations in a parallel environment

### ISSUE THREAD

**Issue by ranc-n** [TillF/ppso#2]
Hi,

I have been able to launch ppso runs on a parallel environment building on Rmpi -- thank you for providing such a useful tool to the community!

I typically execute a sbatch file that contains (see example below for 90 slaves):
`srun -n 91 R CMD BATCH --no-save --no-restore 1_ppso.R`

In 1_ppso.R, I execute a single run of `optim_ppso_robust()`, and then end the script with `mpi.close.Rslaves()`. Note that 1_ppso.R is calling a more complex objective function script, relying on a c++ program (for computationally demanding calculations). This works great. 

I am now interested in launching several `optim_ppso_robust()` sequentially. I have tried different options:
- Multiple `optim_ppso_robust()` calls within 1_ppso.R and closing the overall script with `mpi.close.Rslaves()`.
- Multiple `optim_ppso_robust()` calls within 1_ppso.R `and using mpi.close.Rslaves()` after each call.
- Multiple srun within the sbatch file.
=> I have encountered issues with every option. My preference would be to repetitively call `optim_ppso_robust()` from 1_ppso.R.

It seems the next natural step is to launch a job array. I wonder if you had any alternative suggestions?

Thank you very much for your help,
Best,

Nathan

**Comment by TillF** [comment]
Nathan,
thanks for using ppso.
If I understand you correctly, you want to execute multiple calls to `optim_ppso_robust()` in one job.
Please note that I am not an expert on the subtleties of Rmpi, but afaik MPI sessions are close on calling `mpi.close.Rslaves()` and cannot be reinitialized, but requires a restart of R (or even a new call from srun).
Thus, option 1 you described will not work. Likewise, `optim_ppso_robust()` also closed the MPI-session (line 141), which has the same effect. Your scenario convinced me that the function should not do that in all cases, so I changed the behavious as follows:

- if optim_ppso_robust() finds an active Rmpi session (i.e. is.loaded("mpi_initialize")), it will NOT close the session on exit
- if optim_ppso_robust() does not find an active Rmpi sessionit will initiate on and close the session on exit. This precludes any 
further use of Rmpi in this R session!

Please update your package and add a the initialization of Rmpi (i.e `library("Rmpi")`) before `optim_ppso_robust()` is called for the first time. This should enable subsequent calls. Please let me know if it worked.
As for your option 3, I do not understand why it failed. However, let us follow the approach described above, which will hopefully solve the issue.

**Comment by ranc-n** [comment]
Thank you very much for your quick response; I can now make sense of my trial results. In the end, I was able to launch an array job so that there is a single srun of a single `optim_ppso_robust()`per sbatch file, but I can launch many jobs efficiently.

I will install ppso and Rmpi on a different cluster next month, and will be able to try the update you kindly provided there. I will keep you posted

Thanks again for your help!

Nathan
