### ISSUE TITLE
Odd number of function calls (n_iter * n_particles * n_cores)

### ISSUE THREAD

**Issue by ranc-n** [TillF/ppso#3]
Hi,

Apologies for opening another issue in a short time lapse. I had a ppso setup that worked well on one computer cluster. I recently moved to a second cluster where I am experiencing a few issues (using the same exact scripts).

In my test setup, I use 10 particles, 2 iterations and require 5 slaves. I am therefore expecting 20 function calls (total), and should find 20 lines in my ppso log file. It is indeed the case in my older environment.

On the new cluster environment, I actually seem to get 120 function calls. There are 120 lines in the log file. I require 6 cores (1 for the master + 5 for the slaves) on this job and it seems that the function is executed 10 particles * 2 iterations * 6 cores = 120. The .Rout file indicates that there has been 20 function calls but that does not match what I see in the log file. I trust the log file as in another test I added an external output to the objective function to check how many times it was called -- indeed 120.

I have noticed a couple of warnings/errors I have not seen in my older environment, but it is unclear whether they may be informative.

`mca: base: component_find: unable to open /opt/ohpc/pub/mpi/openmpi-gnu/1.10.7/lib/openmpi/mca_btl_openib: librdmacm.so.1: cannot open shared object file: No such file or directory (ignored)`

`Warning messages:
1: In prepare_mpi_cluster(nslaves = globvars$nslaves, working_dir_list = working_dir_list,  :
  Number of specified slaves exceeds number of available slaves.
2: In init_particles(lhc_init) :
  Package lhs not installed, lhs_init disabled
`

Have you ever encountered this kind of issue before? Do you have any suggestion of possible directions to explore?

Thank you in advance for your help,
Best,

Nathan

**Comment by TillF** [comment]
Thanks for using ppso and your critical assessment.
I am not completely sure what causes this behaviour. However, the message "Number of specified slaves exceeds number of available slaves" suggests that in your current environment the five workers cannot be detected. I suspect, instead, each of the six cores runs an independent serial optimization. As the log-file is written in "append" mode, all instances add their calls to it, resulting in 120 calls. Conversely, the .Rout file only contains the output of one core, as it created in a different mode.
Baseline: Rmpi doesn't work on your new environment as it is supposed to. Sometimes such problems can be sorted out by modifying the way the script is invoked and the job script (if any): mpirun / srun / orterun; with or without mca-flag; argument n=1 or actual number of requested slaves; argument "nodes" in job-script ....
I recommend you try to find the correct settings by getting the simple examples of Rmpi working correctly. If you do, please post the solution here - I am currently facing a similar issue after our compute server has been updated...

**Comment by ranc-n** [comment]
Thanks a lot for your feedback. It looks like I may have found a solution that works in my new environment. R script set up:
particles = 10
iterations = 2
slaves = 5

Sbatch set up:
`#SBATCH -n 6`
`#SBATCH -N 1`
`mpirun -np 1 --mca mpi_warn_on_fork 0 R CMD BATCH --no-save --no-restore ppso_script.R`

I have the expected outputs but there are some odd behaviors and warnings:

(1) When doing sacct, the job appears "pending" while actually running (I see that it prints outputs)

(2) The exit status is "failed"

(3) in .Rout:
`WARNING: ignoring environment value of R_HOME`

(4) in .err:
`mpirun has exited due to process rank 0 with PID 12898 on
node hbcomp-025 exiting improperly. There are three reasons this could occur:
`

`1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.`

`2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"`

`3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.`

`This may have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).`

`You can avoid this message by specifying -quiet on the mpirun command line.`

**Comment by TillF** [comment]
Thanks for sharing your solution.
I have no idea about (1) and (3). As for (2) and (4), I vaguely remember that I had trouble implementing a graceful termination of the script (and MPI-session) in a a way that worked on different MPI-implementations. I suppose this doesn't influence the actual functionality, but I agree that these warnings are a bit unnerving. I'll try to look at this as soon as we get our cluster running again.

**Comment by ranc-n** [comment]
Adding `--mca orte_allowed_exit_without_sync 1` solved (2) and (4). The status of the job is now "completed" as opposed to "failed". My current run line is thus:

`mpirun -np 1 --mca mpi_warn_on_fork 0 --mca orte_allowed_exit_without_sync 1 R CMD BATCH --no-save --no-restore ppso_script.R`

The job is still "pending" although actually running, but I am not as much concerned by that. Instead, next task is to check if that runs across multiple nodes.

P.S. Feel free to close the issue as the "original" problem has been resolved.

**Comment by TillF** [comment]
Thanks for sharing your solution!
