### ISSUE TITLE
cannot install ppso

### ISSUE THREAD

**Issue by mforoughifar** [TillF/ppso#5]
> install.packages("devtools")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/M17/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
also installing the dependencies ‘cli’, ‘rcmdcheck’, ‘sessioninfo’

  There are binary versions available but the source versions are later:
            binary source needs_compilation
cli          2.5.0  3.1.0              TRUE
rcmdcheck    1.3.3  1.4.0             FALSE
sessioninfo  1.1.1  1.2.2             FALSE
devtools     2.4.1  2.4.3             FALSE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/cli_2.5.0.zip'
Content type 'application/zip' length 534931 bytes (522 KB)
downloaded 522 KB

package ‘cli’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\M17\AppData\Local\Temp\RtmpA1MVKj\downloaded_packages
installing the source packages ‘rcmdcheck’, ‘sessioninfo’, ‘devtools’

trying URL 'https://cran.rstudio.com/src/contrib/rcmdcheck_1.4.0.tar.gz'
Content type 'application/x-gzip' length 73522 bytes (71 KB)
downloaded 71 KB

trying URL 'https://cran.rstudio.com/src/contrib/sessioninfo_1.2.2.tar.gz'
Content type 'application/x-gzip' length 170924 bytes (166 KB)
downloaded 166 KB

trying URL 'https://cran.rstudio.com/src/contrib/devtools_2.4.3.tar.gz'
Content type 'application/x-gzip' length 372413 bytes (363 KB)
downloaded 363 KB

* installing *source* package 'sessioninfo' ...
** package 'sessioninfo' successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'cli' 2.5.0 is being loaded, but >= 3.1.0 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'sessioninfo'
* removing 'C:/Users/M17/Documents/R/win-library/3.6/sessioninfo'
Warning in install.packages :
  installation of package ‘sessioninfo’ had non-zero exit status
ERROR: dependency 'sessioninfo' is not available for package 'rcmdcheck'
* removing 'C:/Users/M17/Documents/R/win-library/3.6/rcmdcheck'
Warning in install.packages :
  installation of package ‘rcmdcheck’ had non-zero exit status
ERROR: dependencies 'rcmdcheck', 'sessioninfo' are not available for package 'devtools'
* removing 'C:/Users/M17/Documents/R/win-library/3.6/devtools'
Warning in install.packages :
  installation of package ‘devtools’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\M17\AppData\Local\Temp\RtmpA1MVKj\downloaded_packages’
> devtools::install_github("TillF/ppso")
Error in loadNamespace(name) : there is no package called ‘devtools’

**Comment by TillF** [comment]
The last line of the error message exactly describe the source of the error (there is no package called ‘devtools’), the first three lines its reason and remedy (install Rtools).

However, using devtools is just a convenience solution. If you are unable to get RTools and devtools running, you may also download the files (green button "Code", "Download ZIP") and proceed following [these intructions](https://stackoverflow.com/questions/30989027/how-to-install-a-package-from-a-download-zip-file/30989367).
